name: todo_list_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  android_alarm_manager: ^2.0.2
  firebase_core: ^2.30.1
  cloud_firestore: ^4.3.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.1
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
