// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZzhyqtka0FvT1LAleeY5Nsc4uF428OPU',
    appId: '1:347366254520:web:e70fabcc7585ab4043514d',
    messagingSenderId: '347366254520',
    projectId: 'finalproject-eabd8',
    authDomain: 'finalproject-eabd8.firebaseapp.com',
    storageBucket: 'finalproject-eabd8.appspot.com',
    measurementId: 'G-VL8FXV2JNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx99xYf6SgbJldyv44otMfjBhpckUwo-c',
    appId: '1:347366254520:android:348b01ea569b610d43514d',
    messagingSenderId: '347366254520',
    projectId: 'finalproject-eabd8',
    storageBucket: 'finalproject-eabd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn59cmUF3IgzxeGysdtRhYXxzrGZciPLY',
    appId: '1:347366254520:ios:bb6ac33f9f4cb18843514d',
    messagingSenderId: '347366254520',
    projectId: 'finalproject-eabd8',
    storageBucket: 'finalproject-eabd8.appspot.com',
    iosBundleId: 'com.example.todoList1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn59cmUF3IgzxeGysdtRhYXxzrGZciPLY',
    appId: '1:347366254520:ios:bb6ac33f9f4cb18843514d',
    messagingSenderId: '347366254520',
    projectId: 'finalproject-eabd8',
    storageBucket: 'finalproject-eabd8.appspot.com',
    iosBundleId: 'com.example.todoList1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZzhyqtka0FvT1LAleeY5Nsc4uF428OPU',
    appId: '1:347366254520:web:cc436ec7ee09a8ac43514d',
    messagingSenderId: '347366254520',
    projectId: 'finalproject-eabd8',
    authDomain: 'finalproject-eabd8.firebaseapp.com',
    storageBucket: 'finalproject-eabd8.appspot.com',
    measurementId: 'G-MXH7S61M9H',
  );
}
